"""create initial friday tables

Revision ID: 2c3fbbbaab0b
Revises: 
Create Date: 2026-08-17 15:32:44.955340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c3fbbbaab0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_tasks_status_due'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('idx_audit_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_settings')
    op.drop_table('tool_permissions')
    op.drop_index(op.f('idx_metrics_sampled_at'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('idx_reminders_enabled_time'), table_name='reminders')
    op.drop_table('reminders')
    op.alter_column('conversations', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('conversations', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('conversations', 'archived_at')
    op.drop_column('conversations', 'mode')
    op.add_column('memories', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('memories', sa.Column('key', sa.String(length=255), nullable=False))
    op.add_column('memories', sa.Column('value', sa.Text(), nullable=False))
    op.add_column('memories', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('memories', sa.Column('active', sa.Boolean(), nullable=False))
    op.alter_column('memories', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_memories_active_importance'), table_name='memories')
    op.create_index(op.f('ix_memories_key'), 'memories', ['key'], unique=False)
    op.drop_constraint(op.f('memories_source_message_id_fkey'), 'memories', type_='foreignkey')
    op.drop_constraint(op.f('memories_importance_check'), 'memories', type_='check')
    op.drop_column('memories', 'memory_type')
    op.drop_column('memories', 'content')
    op.drop_column('memories', 'is_active')
    op.drop_column('memories', 'importance')
    op.drop_column('memories', 'source_message_id')
    op.alter_column('messages', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('messages', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('idx_messages_conversation_created'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_constraint(op.f('messages_role_check'), 'messages', type_='check')
    op.drop_column('messages', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.create_check_constraint(op.f('messages_role_check'), 'messages', "role = ANY (ARRAY['system'::text, 'user'::text, 'assistant'::text, 'tool'::text])")
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('idx_messages_conversation_created'), 'messages', ['conversation_id', 'created_at'], unique=False)
    op.alter_column('messages', 'model',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('messages', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('memories', sa.Column('source_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('memories', sa.Column('importance', sa.SMALLINT(), server_default=sa.text('5'), autoincrement=False, nullable=False))
    op.add_column('memories', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('memories', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('memories', sa.Column('memory_type', sa.TEXT(), server_default=sa.text("'fact'::text"), autoincrement=False, nullable=False))
    op.create_check_constraint(op.f('memories_importance_check'), 'memories', 'importance >= 1 AND importance <= 10')
    op.create_foreign_key(op.f('memories_source_message_id_fkey'), 'memories', 'messages', ['source_message_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_memories_key'), table_name='memories')
    op.create_index(op.f('idx_memories_active_importance'), 'memories', ['is_active', sa.literal_column('importance DESC')], unique=False)
    op.alter_column('memories', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('memories', 'active')
    op.drop_column('memories', 'source')
    op.drop_column('memories', 'value')
    op.drop_column('memories', 'key')
    op.drop_column('memories', 'category')
    op.add_column('conversations', sa.Column('mode', sa.TEXT(), server_default=sa.text("'local'::text"), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('conversations', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('conversations', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('reminders',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('remind_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('recurrence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('fired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('reminders_task_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('reminders_pkey'))
    )
    op.create_index(op.f('idx_reminders_enabled_time'), 'reminders', ['is_enabled', 'remind_at'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cpu_percent', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('ram_percent', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('gpu_percent', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('gpu_memory_percent', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('sampled_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_metrics_pkey'))
    )
    op.create_index(op.f('idx_metrics_sampled_at'), 'system_metrics', [sa.literal_column('sampled_at DESC')], unique=False)
    op.create_table('tool_permissions',
    sa.Column('tool_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('permission_mode', sa.TEXT(), server_default=sa.text("'ask'::text"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("permission_mode = ANY (ARRAY['deny'::text, 'ask'::text, 'allow'::text])", name=op.f('tool_permissions_permission_mode_check')),
    sa.PrimaryKeyConstraint('tool_name', name=op.f('tool_permissions_pkey'))
    )
    op.create_table('app_settings',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('app_settings_pkey'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('idx_audit_created_at'), 'audit_log', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=False),
    sa.Column('priority', sa.SMALLINT(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status = ANY (ARRAY['open'::text, 'in_progress'::text, 'done'::text, 'cancelled'::text])", name=op.f('tasks_status_check')),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name=op.f('tasks_priority_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('idx_tasks_status_due'), 'tasks', ['status', 'due_at'], unique=False)
    # ### end Alembic commands ###
